#-----------------------------
# Furuikeya English Strings
#-----------------------------

# Main Strings
main:
    title: 'Furuikeya'

twitter:
    open: 'Initializing Twitter connection//INFO'
    fetch: 'Fetching tweets for kigo : {kigo}//DEBUG'

controller:
    not_enough: 'Not enough material to finish the haiku with these tweets. Continuing...//WARNING'